#!/bin/bash -xe 

#install packages
sudo su -
yum update -y
yum install git -y
amazon-linux-extras install -y lamp-mariadb10.2-php7.2 php7.2
yum install -y httpd mariadb-server
systemctl start httpd
systemctl enable httpd
systemctl is-enabled httpd

##add user to Apache group and grant permissions to /var/www
usermod -a -G apache ec2-user
chown -R ec2-user:apache /var/www
chmod 2775 /var/www && find /var/www -type d -exec sudo chmod 2775 {} \;
find /var/www -type f -exec sudo chmod 0664 {} \;
cd ${MOUNT_POINT}
sudo chmod -R 755 ${MOUNT_POINT}

if ! [ -e /var/www/html/CliXX_Retail_Repository ]; then
    git clone ${GIT_REPO}
    cp -r CliXX_Retail_Repository/* ${MOUNT_POINT}

else
    echo "Directory 'CliXX_Retail_Repository' already exists."

fi

DB_HOST=$(echo "${RDS_INSTANCE}" | sed 's/':3306'//g')

#replace DB Hostname in configuration file
sed -i "s/'wordpress-db.cc5iigzknvxd.us-east-1.rds.amazonaws.com'/'$${DB_HOST}'/g" /var/www/html/wp-config.php

#grant file ownership of /var/www & its contents to apache user
chown -R apache /var/www

#grant group ownership of /var/www & contents to apache group
chgrp -R apache /var/www

#change directory permissions
chmod 2775 /var/www
find /var/www -type d -exec sudo chmod 2775 {} \;

#recursively change file permission of /var/www & subdir to add group write perm
find /var/www -type f -exec sudo chmod 0664 {} \;
 
mysql -h "$${DB_HOST}" -u "${DB_USER}" -p"${DB_PASSWORD}" <<EOF
    use wordpressdb;
    Update wp_options SET option_value="${LB_DNS}" WHERE option_value like '%CliXX%';
EOF

#restart Apache
systemctl restart httpd
service httpd restart

#enable httpd
systemctl enable httpd
sudo /sbin/sysctl -w net.ipv4.tcp_keepalive_time=200 net.ipv4.tcp_keepalive_intvl=200 net.ipv4.tcp_keepalive_probes=5